<?php
/**
 * Drawshield PHP Source File
 *
 * Description...
 *
 * @author Karl R. Wilcox <karl@karlwilcox.com>
 * @copyright Karl R. Wilcox 2014
 * @license http://www.apache.org/licenses/LICENSE-2.0
 * Date: 08/09/14
 * Time: 14:47
 */

$charge['file'] = chose_by_modifier($node, $folder, $chargeKey, array ( 
		'head-only' => 'head',
		'passant' => null,
		'sejant' => null,
		'courant' => null,
		'rampant' => null
	));

