<?php /* Copyright 2010-2021 Karl Wilcox, Mattias Basaglia

This file is part of the DrawShield.net heraldry image creation program

    DrawShield is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

     DrawShield is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with  DrawShield.  If not, see https://www.gnu.org/licenses/. */
$rivet = '<g>
  <path d="m16.78,2.14   c4.973,3.125 6.468,9.687 3.345,14.66 -3.125,4.973 -9.687,6.468 -14.66,3.345 -4.973,-3.125 -6.468,-9.687 -3.345,-14.66 3.125,-4.973 9.687,-6.468 14.66,-3.345   z " id="path3001" style="opacity:0.5;fill:#999999;stroke:#000000"/>
  <path d="m16.76,2.1   c4.973,3.125 12.24,10.58 7.897,17.23 -3.892,5.965 -14.05,3.955 -19.02,0.83 0,0 5.821,-1.316 9.128,-6.602 3.627,-5.858 1.338,-11.57 1.995,-11.45   z " id="path3779" style="opacity:0.5;fill:#4d4d4d;stroke:#000000"/>
</g>';
