<?php /* Copyright 2010-2021 Karl Wilcox, Mattias Basaglia

This file is part of the DrawShield.net heraldry image creation program

    DrawShield is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

     DrawShield is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with  DrawShield.  If not, see https://www.gnu.org/licenses/.
 */


$ordinary['body'] = '<path d="M100.5,400.5 L500.5,0.5 L900.5,400.5 L650.5,400.5 L500.5,250.5 L350.5,400.5 L100.5,400.5" stroke="none" />
    <path d="M-99.5,1200.5 L500.5,600.5 L1100.5,1200.5 L850.5,1200.5 L500.5,850.5 L150.5,1200.5 L-99.5,1200.5"  stroke="none"/>
    <path d="M-49.5,400.5 L1050.5,400.5 L1050.5,600.5 L-49.5,600.5 L-49.5,400.5 z"  stroke="none"/>';