<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */


$y = ($layout->cross_point->y - 500);

$ordinary['body'] = "<path
    transform='translate(0, $y)'
    d='m 698,415 57,57 28,28 -283,283 -85,-85 57,-57 28,29 170,-170 -29,-28 57,-57 z m -339,113 -57,57 -85,-85 283,-283 85,85 -57,57 -28,-29 -170,170 29,28 z M 118,825 415,528 471,585 175,882 118,825 z M 528,415 825,118 882,175 585,472 528,415 z M 415,472 472,415 585,528 528,585 415,472 z M 641,698 698,641 884,827 827,884 641,698 z M 118,175 175,118 358,302 302,358 118,175 z'
/>";

