<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */


$ordinary['body'] = '<path d="m 585,698 -57,57 -28,28 -283,-283 85,-85 57,57 -29,28 170,170 28,-29 57,57 z M 472,359 415,302 500,217 783,500 698,585 641,528 670,500 500,330 472,359 z M -16.6,-73.2 472,415 415,472 -73.2,-16.6 -16.6,-73.2 z M 585,528 l 495,492 -60,60 -492,-495 57,-57 z M 528,415 585,472 472,585 415,528 528,415 z M 302,641 358,698 -17,1070 -73.5,1020 302,641 z m 718,-714.5 50,56.5 -372,375 -57,-56 379,-375.5 z" />';
