<?php /* Copyright 2010-2021 Karl Wilcox, Mattias Basaglia

This file is part of the DrawShield.net heraldry image creation program

    DrawShield is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

     DrawShield is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with  DrawShield.  If not, see https://www.gnu.org/licenses/.
 */


$ordinary['shape_spec'] = 'X-8Y600B577C208e408g600';
if ( $node->getAttribute('number') == '2') $ordinary['shape_spec'] .= '    X1008Y600c600e408G208H577';

// :w
$ordinary['chargesOn'] = '200,975,150,150/125,885,140,140:275,1040,140,140/200,975,120,120:100,875:300,1075';