<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */


$ordinary['body'] = '<polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" />
             <g transform="translate(100,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(200,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(300,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(400,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(500,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(600,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(700,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(800,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /><polygon points="98,0 102,0 102,1200 98,1200" /></g>
             <g transform="translate(900,0)"><polygon points="49.5,0 50.5,0 50.5,1200 49.5,1200" /></g>
             <path d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,100)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,200)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,300)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,400)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,500)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,600)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,700)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,800)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,900)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,1000)" d="M0,49.5h1000v1h-1000z M0,98h1000v4h-1000z" />
             <path transform="translate(0,1100)" d="M0,49.5h1000v1h-1000z" />
             ';
