<?php /* Copyright 2010 Karl R. Wilcox 

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. */


if ( $node->getAttribute('number') == '2')
  $ordinary['shape_spec'] =  array( 'NC' => 'X-8Y-8B577C816e408g1216    X1008Y-8c1216e408G816H577', 'CH' => 'X-8Y292B577C616e408g916   X1008Y292c916e408G616H577' );
else
  $ordinary['shape_spec'] =  array( 'NC' => 'X-8Y-8B577C816e408g1216', 'CH' => 'X-8Y292B577C616e408g916' );
