<?php /* Copyright 2010-2021 Karl Wilcox, Mattias Basaglia

This file is part of the DrawShield.net heraldry image creation program

    DrawShield is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see https://www.gnu.org/licenses/. */

$messages->addMessage('licence','Pallium - https://commons.wikimedia.org/wiki/User:Akigka');
$ordinary['body'] = '   <g
     id="g858"
     transform="matrix(10.806592,0,0,10.806592,-997.1087,-4423.7)">
    <path
       d="m 179.16,404.77 -40.55,42.9 -40.167,-42.6 -10.734,-0.13 0.364,15.19 42.247,40.02 v 32.54 h 17.42 l 0.72,-32.24 39.69,-40.43 0.1,-15.25 z"
       id="path852" />
    <path
       d="m 173.22,404.93 -34.7,36.4 -33.99,-36.04 h -3.56 l 37.56,39.86 38.06,-40.19 z"
       id="path854" />
    <path
       d="m 188.04,422.34 -37.94,39.48 -0.61,32.45 h -20.92 v -33.3 l -40.436,-38.26 0.443,3.97 36.783,35.07 0.44,34.3 v 1.72 l -1.31,11.34 1.78,0.25 1.59,-11.59 h 1.13 l -1.63,13.12 1.78,0.25 1.66,-13.37 h 1.03 l -1.62,15.31 1.78,0.16 1.65,-15.47 h 0.66 l -0.88,16.06 1.82,0.1 0.84,-16.15 h 0.84 l -0.28,16.83 1.78,0.1 0.29,-16.89 h 0.78 l 0.37,17.08 h 1.81 l -0.37,-17.08 h 0.69 l 0.83,16.35 h 1.82 l -0.84,-16.32 h 0.44 l 1.31,16.19 1.81,-0.16 -1.31,-16.03 h 0.59 l 1.78,13.19 1.81,-0.19 -1.77,-13 h 1.06 l 1.88,11.67 1.78,-0.34 -1.14,-11.49 1.01,-34.87 34.54,-36 z"
       id="path856" />
  </g>
';
